CREATE TABLE "performance_metrics" (
	"id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"page_title" text,
	"user_id" text,
	"session_id" text,
	"lcp" real,
	"fid" real,
	"cls" real,
	"fcp" real,
	"ttfb" real,
	"tti" real,
	"dom_content_loaded_time" real,
	"load_time" real,
	"first_paint_time" real,
	"connection_type" varchar(50),
	"effective_type" varchar(20),
	"user_agent" text,
	"device_type" varchar(20),
	"screen_resolution" varchar(20),
	"viewport" varchar(20),
	"browser_name" varchar(50),
	"browser_version" varchar(50),
	"ip" varchar(46),
	"country" varchar(2),
	"region" varchar(100),
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "performance_summary" (
	"id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"date" text NOT NULL,
	"hour" integer,
	"avg_lcp" real,
	"avg_fid" real,
	"avg_cls" real,
	"avg_fcp" real,
	"avg_ttfb" real,
	"avg_tti" real,
	"avg_load_time" real,
	"sample_count" integer DEFAULT 0 NOT NULL,
	"p50_lcp" real,
	"p90_lcp" real,
	"p95_lcp" real,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
