// Usage: node gl-qa.mjs <out-prefix> [base] — dev server only (?gl-software).
import { chromium } from '@playwright/test'
const [prefix, base = 'http://localhost:3200'] = process.argv.slice(2)
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const [vw, vh] = (process.env.QA_SIZE ?? '1280x720').split('x').map(Number)
const page = await browser.newPage({ viewport: { width: vw, height: vh } })
const logs = []
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) logs.push(`[${m.type()}] ${m.text()}`) })
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`))
await page.goto(`${base}/en?gl-software`, { waitUntil: 'load', timeout: 120000 })
const gl = await page.waitForSelector('[data-hero][data-gl="on"]', { timeout: 60000 }).then(() => 'on').catch(() => 'off')
console.log('gl:', gl)
await page.waitForTimeout(2000)
await page.mouse.move(Math.round(vw * 0.5), Math.round(vh * 0.35))
await page.waitForTimeout(600)
await page.screenshot({ path: `${prefix}-lens.png` })
await page.mouse.move(Math.round(vw * 0.25), Math.round(vh * 0.78))
await page.mouse.down(); await page.mouse.up()
await page.waitForTimeout(350)
console.log('gl at ripple:', await page.evaluate(() => document.querySelector('[data-hero]').dataset.gl ?? 'off'))
await page.screenshot({ path: `${prefix}-ripple.png` })
console.log(logs.slice(0, 8).join('\n'))
await browser.close()
